baseURL = "https://pawelgrzybek.com/"
title = "pawelgrzybek.com"
disableKinds = ["taxonomy","taxonomyTerm"]

disqusShortname = "studiorgb"
pygmentsCodeFences = true
pygmentsUseClasses = true

# waitin for 0.38 to enable it
# [frontmatter]
# date  = [":filename", ":default"]

[permalinks]
  posts = "/:slug/"
