baseURL = "https://pawelgrzybek.com/"
title = "pawelgrzybek.com"
disableKinds = ["taxonomy","taxonomyTerm"]

disqusShortname = "studiorgb"
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsStyle = "manni"

[permalinks]
  posts = "/:slug/"
